using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;


public class Elemento : MonoBehaviour
{

    public GameObject obj;
    public GameObject Erro;
    public Camera camera;
    public Image bg;
    public Text Nome;
    public Text NomeLatin;
    public Text Simbolo;
    public Text Numero;
    public Text AnoDescoberta;
    public Text CAS;
    public Text Descobridor;
    public Text Valor;
    public Text K;
    public Text L;
    public Text M;
    public Text N;
    public Text O;
    public Text P;
    public Text Q;
    public Text E;
    public Text Eletrons;
    public Text Protons;
    public Text Neutrons;
    public Text NumeroAtomico;
    public Text PesoAtomico;
    public Text PontoDeFusao;
    public Text PontoDeEbulicao;
    public Text Fase;
    public Text Valencia;
    public Text Periodo;
    public Text Grupo;
    public Text Quadra;
    public Text Configuracao;
    public Text Carga;
    public Text PotenciAIonizacao;
    public Text RaioAtomico;
    public Text RaioCovalente;
    public Text RaioDeVanDerWaals;
    public Text Eletronegatividade;
    public Text CamadaValencia;
    public Text Afinidade;
    public Text CondutividadeEletrica;
    public Text TipoEletronico;
    public Text TipoMagnetico;
    public Text Sensibilidade;
    public Text Resistividade;
    public Text PontoDeSuperconducao;
    public Text info;
    public Text Densidade;
    public void MostraMaisSobreOElemento(Text numeroAtomico){
        int num = 0;
        
        num = int.Parse(numeroAtomico.text) - 1;
        if(num < 0){
            return;
        }else{
            Debug.Log(num);
            bg.color = TileStyleHolder.Instance.TileStyle [num].Background;
            camera.backgroundColor = TileStyleHolder.Instance.TileStyle [num].Background;
            SetElemento(num);
            obj.SetActive(true);
            GameManager.GAMESTATE = "Elemento";
        }
    }  
    public void fechar(){
        obj.SetActive(false);
        Erro.SetActive(false);
        bg.color = TileStyleHolder.Instance.TileStyle [119].Background;
        camera.backgroundColor = TileStyleHolder.Instance.TileStyle [119].Background;
        GameManager.GAMESTATE = "Normal";
    }
    private void SetElemento(int num){
    
        SetDefaultPrefix();
        Debug.Log(num);
        switch (num)
        {
            case 0:
    
                Hidrogenio();

            break;
            case 1:
                Helio();
            break;
            case 2:
                Litio();
            break;
            case 3:
                Berilio();
            break;
            case 4:
                Boro();
            break;
            case 5:
                Carbono();
            break;
            case 6:
                Nitrogenio();
            break;
            case 7:
                Oxigenio();
            break;
            case 8:
                Fluor();
            break;
            case 9:
                Neonio();
            break;
            case 10:
                Sodio();
            break;
            case 11:
                Magnesio();
            break;
            case 12:
                Aluminio();
            break;
            case 13:
                Silicio();
            break;
            case 14:
                Fosforo();
            break;
            case 15:
                Enxofre();
            break;
            case 16:
                CLoro();
            break;
            case 17:
                Argonio();
            break;
            case 18:
                Potassio();
            break;
            case 19:
                Calcio();
            break;
            case 20:
            Escandio();
            break;
            case 21:
            Titanio();
            break;
            Vanadio();
            case 22:
            Cromio();
            break;

            case 23:
            Manganes();
            break;
            case 24:
            Ferro();
            break;
            case 25:
            Cobalto();
            break;
            default:
                ElementoIncompleto();
            break;
        }

    }

    private void ElementoIncompleto(){
        Erro.SetActive(true);
        obj.SetActive(false);
    }

    private void SetDefaultPrefix(){
        AnoDescoberta.text = "Descoberto em: ";
        CAS.text = "Numero CAS: ";
        Descobridor.text = "Descoberto por: ";
        Valor.text = "Custo por 100g em reias: ";
        K.text = "K";
        L.text = "L";
        M.text = "M";
        N.text = "N";
        O.text = "O";
        P.text = "P";
        Q.text = "Q";
        E.text = "E";
        Eletrons.text = "Eletrons: ";
        Protons.text = "Protons: ";
        Neutrons.text = "Neutrons: ";
        NumeroAtomico.text = "";
        PesoAtomico.text = "Peso Atomico: ";
        Densidade.text = "Densidade: ";
        PontoDeFusao.text = "Ponto de Fusao: ";
        PontoDeEbulicao.text = "Ponto de Ebulicao: ";
        Fase.text = "Fase: ";
        Valencia.text = "Valencia: ";
        Periodo.text = "Periodo: ";
        Grupo.text = "Grupo: ";
        Quadra.text = "Quadra: ";
        Configuracao.text = "Configuracao de eletrons: ";
        Carga.text = "Carga de Ions: ";
        PotenciAIonizacao.text="Potecial de ionizacao: ";
        RaioAtomico.text = "Raio atomico: ";
        RaioCovalente.text = "Raio covalente: ";
        RaioDeVanDerWaals.text = "Raio de Van der Waals: ";
        Eletronegatividade.text = "Eletronegatividade: ";
        CamadaValencia.text = "Valencia: ";
        Afinidade.text = "Afinidade de eletrons: ";
        CondutividadeEletrica.text = "Condutividade eletrica: ";
        TipoEletronico.text = "Tipo eletrico: ";
        TipoMagnetico.text = "Tipo magnetico: ";
        Sensibilidade.text = "Sensibilidade magnetica(Mol/L):";
        Resistividade.text = "Resistividade: ";
        PontoDeSuperconducao.text = "Ponto de supercondução: ";
        info.text = "";
    }
    // Start is called before the first frame update
    void Start()
    {
        obj.SetActive(false);
        Erro.SetActive(false);
    }

    // Update is called once per frame
    void Update()
    {
        
    }
    public void Hidrogenio(){
        Nome.text = "Hidrogenio";
        NomeLatin.text = "Hydrogenium";
        AnoDescoberta.text += "1766";
        CAS.text += "CAS1333-74-0";
        Descobridor.text += "Henry Cavewndish";
        Valor.text += "65,14";
        K.text += "1";
        L.text += "0";
        M.text += "0";
        N.text += "0";
        O.text += "0";
        P.text += "0";
        Q.text += "0";
        E.text += "0";
        Eletrons.text += "1";
        Protons.text += "1";
        Neutrons.text += "1";
        NumeroAtomico.text += "1";
        Numero.text = "1";
        Simbolo.text = "H";
        PesoAtomico.text += "1.00784";
        Densidade.text += "0.0000899";
        PontoDeFusao.text += "-259.14";
        PontoDeEbulicao.text += "-252.87";
        Fase.text += "Gasoso";
        Valencia.text += "I";
        Periodo.text += "1";
        Grupo.text += "IA";
        Quadra.text += "s - quadra";
        Configuracao.text += "1s¹";
        Carga.text += "H+,H-";
        PotenciAIonizacao.text += "13.53";
        RaioAtomico.text += "53";
        RaioCovalente.text += "38";
        RaioDeVanDerWaals.text += "120";
        Eletronegatividade.text += "2.2";
        CamadaValencia.text += "I";
        Afinidade.text += "72.8";
        CondutividadeEletrica.text += "---";
        TipoEletronico.text += "---";
        TipoMagnetico.text += "Diamagnetico";
        Sensibilidade.text += "-2.23*10^-9";
        Resistividade.text += "---";
        PontoDeSuperconducao.text += "---";
        info.text += "";
    }
    public void Helio(){
        Nome.text = "Helio";
        NomeLatin.text = "Helium";
        AnoDescoberta.text += "1895";
        CAS.text += "CAS7440-59-7";
        Descobridor.text += "Pierre Jules Cesar Janssen";
        Valor.text += "13,03";
        K.text += "2";
        L.text += "0";
        M.text += "0";
        N.text += "0";
        O.text += "0";
        P.text += "0";
        Q.text += "0";
        E.text += "0";
        Eletrons.text += "2";
        Protons.text += "2";
        Neutrons.text += "2";
        NumeroAtomico.text += "2";
        Numero.text = "2";
        Simbolo.text = "He";
        PesoAtomico.text += "4.0026";
        Densidade.text += "0.00017846";
        PontoDeFusao.text += "-272.2";
        PontoDeEbulicao.text += "-268.9";
        Fase.text += "Gasoso";
        Valencia.text += "O";
        Periodo.text += "1";
        Grupo.text += "VIIIA";
        Quadra.text += "s - quadra";
        Configuracao.text += "1s²";
        Carga.text += "---";
        PotenciAIonizacao.text += "24.47";
        RaioAtomico.text += "31";
        RaioCovalente.text += "32";
        RaioDeVanDerWaals.text += "140";
        Eletronegatividade.text += "---";
        CamadaValencia.text += "O";
        Afinidade.text += "0";
        CondutividadeEletrica.text += "---";
        TipoEletronico.text += "---";
        TipoMagnetico.text += "Diamagnetico";
        Sensibilidade.text += "-2.36*10^-11";
        Resistividade.text += "---";
        PontoDeSuperconducao.text += "---";
        info.text += "";
    }
    public void Litio(){
        Nome.text = "Litio";
        NomeLatin.text = "Lithium";
        AnoDescoberta.text += "1817";
        CAS.text += "CAS7439-93-2";
        Descobridor.text += "Johan August Arfwedson";
        Valor.text += "46.96";
        K.text += "2";
        L.text += "1";
        M.text += "0";
        N.text += "0";
        O.text += "0";
        P.text += "0";
        Q.text += "0";
        E.text += "0";
        Eletrons.text += "3";
        Protons.text += "3";
        Neutrons.text += "4";
        NumeroAtomico.text += "3";
        Numero.text = "3";
        Simbolo.text = "Li";
        PesoAtomico.text += "6.941";
        Densidade.text += "0.534";
        PontoDeFusao.text += "180.5";
        PontoDeEbulicao.text += "1342.0";
        Fase.text += "Solido";
        Valencia.text += "I";
        Periodo.text += "2";
        Grupo.text += "IA";
        Quadra.text += "s - quadra";
        Configuracao.text += "[He]2s¹ 1s²2s¹";
        Carga.text += "Li+";
        PotenciAIonizacao.text += "5.37";
        RaioAtomico.text += "145";
        RaioCovalente.text += "134";
        RaioDeVanDerWaals.text += "182";
        Eletronegatividade.text += "0.98";
        CamadaValencia.text += "I";
        Afinidade.text += "59.6";
        CondutividadeEletrica.text += "1.1*10^7";
        TipoEletronico.text += "Condutor";
        TipoMagnetico.text += "Paramagnetico";
        Sensibilidade.text += "1.78*10^-10";
        Resistividade.text += "9.4*10^-8";
        PontoDeSuperconducao.text += "";
        info.text += "";
    }
     public void Berilio(){
        Nome.text = "Berilio";
        NomeLatin.text = "Beryllium";
        AnoDescoberta.text += "1798";
        CAS.text += "CAS7440-41-7";
        Descobridor.text += "Louis-Nivolas Vauquelin";
        Valor.text += "468.30";
        K.text += "2";
        L.text += "2";
        M.text += "0";
        N.text += "0";
        O.text += "0";
        P.text += "0";
        Q.text += "0";
        E.text += "0";
        Eletrons.text += "4";
        Protons.text += "4";
        Neutrons.text += "5";
        Numero.text = "4";
        Simbolo.text = "Be";
        NumeroAtomico.text += "4";
        PesoAtomico.text += "9.0121";
        Densidade.text += "1.848";
        PontoDeFusao.text += "1278.0";
        PontoDeEbulicao.text += "2970.0";
        Fase.text += "Solido";
        Valencia.text += "II";
        Periodo.text += "2";
        Grupo.text += "IIA";
        Quadra.text += "s - quadra";
        Configuracao.text += "[He]2s² 1s²2s²";
        Carga.text += "Be2+";
        PotenciAIonizacao.text += "9.50";
        RaioAtomico.text += "112";
        RaioCovalente.text += "90";
        RaioDeVanDerWaals.text += "153";
        Eletronegatividade.text += "1.57";
        CamadaValencia.text += "II";
        Afinidade.text += "0";
        CondutividadeEletrica.text += "2.5*10^7";
        TipoEletronico.text += "Condutor";
        TipoMagnetico.text += "Diamagnetico";
        Sensibilidade.text += "-1.136*10^-10";
        Resistividade.text += "4*10^-8";
        PontoDeSuperconducao.text += "0.026";
        info.text += "";
    }
    public void Boro(){
        Nome.text = "Boro";
        NomeLatin.text = "Borum";
        AnoDescoberta.text += "1808";
        CAS.text += "CAS7440-42-8";
        Descobridor.text += "Joseph Louis Gay-Lussac";
        Valor.text += "2,02";
        K.text += "2";
        L.text += "3";
        M.text += "0";
        N.text += "0";
        O.text += "0";
        P.text += "0";
        Q.text += "0";
        E.text += "0";
        Eletrons.text += "5";
        Protons.text += "5";
        Neutrons.text += "6";
        NumeroAtomico.text += "5";
        Numero.text = "5";
        Simbolo.text = "B";
        PesoAtomico.text += "10.811";
        Densidade.text += "2.34";
        PontoDeFusao.text += "2075.8";
        PontoDeEbulicao.text += "3926.8";
        Fase.text += "Solido";
        Valencia.text += "III";
        Periodo.text += "2";
        Grupo.text += "IIIA";
        Quadra.text += "p - quadra";
        Configuracao.text += "[He]2s²2p¹ 1s²2s²2p¹";
        Carga.text += "---";
        PotenciAIonizacao.text += "8.33";
        RaioAtomico.text += "98";
        RaioCovalente.text += "82";
        RaioDeVanDerWaals.text += "192";
        Eletronegatividade.text += "2.04";
        CamadaValencia.text += "III";
        Afinidade.text += "26.7 (Kj/mol)";
        CondutividadeEletrica.text += "0.0001";
        TipoEletronico.text += "Dieletrico";
        TipoMagnetico.text += "Diamagnetico";
        Sensibilidade.text += "-9.41*10^-11";
        Resistividade.text += "10000";
        PontoDeSuperconducao.text += "---";
        info.text += "";
    }
     public void Carbono(){
        Nome.text = "Carbono";
        NomeLatin.text = "Carbonium";
        AnoDescoberta.text += "Antiguidade profunda";
        CAS.text += "CAS7440-44-0";
        Descobridor.text += "Antoine Laurent de Lavoisier";
        Valor.text += "13.11";
        K.text += "2";
        L.text += "4";
        M.text += "0";
        N.text += "0";
        O.text += "0";
        P.text += "0";
        Q.text += "0";
        E.text += "0";
        Eletrons.text += "6";
        Protons.text += "6";
        Neutrons.text += "6";
        NumeroAtomico.text += "6";
        Numero.text = "6";
        Simbolo.text = "C";
        PesoAtomico.text += "12.0107";
        Densidade.text += "2.26";
        PontoDeFusao.text += "3550.5";
        PontoDeEbulicao.text += "4827.0";
        Fase.text += "Solido";
        Valencia.text += "II,IV";
        Periodo.text += "2";
        Grupo.text += "IVA";
        Quadra.text += "p - quadra";
        Configuracao.text += "[He]2s²2p² 1s²2s²2p²";
        Carga.text += "---";
        PotenciAIonizacao.text += "11.22";
        RaioAtomico.text += "77";
        RaioCovalente.text += "77";
        RaioDeVanDerWaals.text += "170";
        Eletronegatividade.text += "2.55";
        CamadaValencia.text += "II,IV";
        Afinidade.text += "153.9";
        CondutividadeEletrica.text += "1*10^5";
        TipoEletronico.text += "Condutor";
        TipoMagnetico.text += "Diamagnetico";
        Sensibilidade.text += "-7.45*10^-11";
        Resistividade.text += "1*10^-5";
        PontoDeSuperconducao.text += "---";
        info.text += "";
    }
     public void Nitrogenio(){
        Nome.text = "Nitrogenio";
        NomeLatin.text = "Nitrogenium";
        AnoDescoberta.text += "1772";
        CAS.text += "CAS7727-37-9";
        Descobridor.text += "Daniel Rutherford";
        Valor.text += "2.19";
        K.text += "2";
        L.text += "5";
        M.text += "0";
        N.text += "0";
        O.text += "0";
        P.text += "0";
        Q.text += "0";
        E.text += "0";
        Eletrons.text += "7";
        Protons.text += "7";
        Neutrons.text += "7";
        NumeroAtomico.text += "7";
        Numero.text = "7";
        Simbolo.text = "N";
        PesoAtomico.text += "14.0067";
        Densidade.text += "0.001251";
        PontoDeFusao.text += "-209.9";
        PontoDeEbulicao.text += "-195.8";
        Fase.text += "Gasoso";
        Valencia.text += "III,IV,V";
        Periodo.text += "2";
        Grupo.text += "VA";
        Quadra.text += "p - quadra";
        Configuracao.text += "[He]2s²2p³ 1s²2s²2p³";
        Carga.text += "N^3-";
        PotenciAIonizacao.text += "14.48";
        RaioAtomico.text += "92";
        RaioCovalente.text += "75";
        RaioDeVanDerWaals.text += "155";
        Eletronegatividade.text += "3.04";
        CamadaValencia.text += "III,IV,V";
        Afinidade.text += "7";
        CondutividadeEletrica.text += "---";
        TipoEletronico.text += "---";
        TipoMagnetico.text += "Diamagnetico";
        Sensibilidade.text += "-1.5*10^-10";
        Resistividade.text += "---";
        PontoDeSuperconducao.text += "---";
        info.text += "";
    }
     public void Oxigenio(){
        Nome.text = "Oxigenio";
        NomeLatin.text = "Oxygenium";
        AnoDescoberta.text += "1774";
        CAS.text += "CAS7782-44-7";
        Descobridor.text += "Michal Sedziwoj";
        Valor.text += "1.64";
        K.text += "2";
        L.text += "6";
        M.text += "0";
        N.text += "0";
        O.text += "0";
        P.text += "0";
        Q.text += "0";
        E.text += "0";
        Eletrons.text += "8";
        Protons.text += "8";
        Neutrons.text += "8";
        NumeroAtomico.text += "8";
        Numero.text = "8";
        Simbolo.text = "O";
        PesoAtomico.text += "15.9994";
        Densidade.text += "0.00142897";
        PontoDeFusao.text += "-218.79";
        PontoDeEbulicao.text += "-182.96";
        Fase.text += "Gasoso";
        Valencia.text += "II";
        Periodo.text += "2";
        Grupo.text += "VIA";
        Quadra.text += "p - quadra";
        Configuracao.text += "[He]2s²2p^4 1s²2s²2p^4";
        Carga.text += "O^2-";
        PotenciAIonizacao.text += "13.56";
        RaioAtomico.text += "48";
        RaioCovalente.text += "66";
        RaioDeVanDerWaals.text += "152";
        Eletronegatividade.text += "3.44";
        CamadaValencia.text += "II";
        Afinidade.text += "141";
        CondutividadeEletrica.text += "---";
        TipoEletronico.text += "---";
        TipoMagnetico.text += "Paramagnetico";
        Sensibilidade.text += "4.27184*10^-8";
        Resistividade.text += "---";
        PontoDeSuperconducao.text += "---";
        info.text += "";
    }
     public void Fluor(){
        Nome.text = "Fluor";
        NomeLatin.text = "Fluorum";
        AnoDescoberta.text += "1886";
        CAS.text += "CAS7782-41-4";
        Descobridor.text += "Ferdinand Frederic Henri Moisan";
        Valor.text += "1.18";
        K.text += "2";
        L.text += "7";
        M.text += "0";
        N.text += "0";
        O.text += "0";
        P.text += "0";
        Q.text += "0";
        E.text += "0";
        Eletrons.text += "9";
        Protons.text += "9";
        Neutrons.text += "10";
        NumeroAtomico.text += "9";
        Numero.text = "9";
        Simbolo.text = "F";
        PesoAtomico.text += "18.9984";
        Densidade.text += "0.001696";
        PontoDeFusao.text += "-219.67";
        PontoDeEbulicao.text += "-188.11";
        Fase.text += "Gasoso";
        Valencia.text += "I,II";
        Periodo.text += "2";
        Grupo.text += "VIIA";
        Quadra.text += "p - quadra";
        Configuracao.text += "[He]2s²2p⁵ 1s²2s²2p⁵";
        Carga.text += "F-";
        PotenciAIonizacao.text += "18.6";
        RaioAtomico.text += "73";
        RaioCovalente.text += "71";
        RaioDeVanDerWaals.text += "147";
        Eletronegatividade.text += "3.98";
        CamadaValencia.text += "I,II";
        Afinidade.text += "328";
        CondutividadeEletrica.text += "---";
        TipoEletronico.text += "---";
        TipoMagnetico.text += "---";
        Sensibilidade.text += "---";
        Resistividade.text += "---";
        PontoDeSuperconducao.text += "---";
        info.text += "";
    }
     public void Neonio(){
        Nome.text = "Neonio";
        NomeLatin.text = "Neon";
        AnoDescoberta.text += "1898";
        CAS.text += "CAS7440-01-9";
        Descobridor.text += "Sir William Ramsay";
        Valor.text += "131,15";
        K.text += "2";
        L.text += "8";
        M.text += "0";
        N.text += "0";
        O.text += "0";
        P.text += "0";
        Q.text += "0";
        E.text += "0";
        Eletrons.text += "10";
        Protons.text += "10";
        Neutrons.text += "10";
        NumeroAtomico.text += "10";
        Numero.text = "10";
        Simbolo.text = "Ne";
        PesoAtomico.text += "20.1797";
        Densidade.text += "0.0009002";
        PontoDeFusao.text += "-248.67";
        PontoDeEbulicao.text += "-246.05";
        Fase.text += "Gasoso";
        Valencia.text += "0";
        Periodo.text += "2";
        Grupo.text += "VIIIA";
        Quadra.text += "p - quadra";
        Configuracao.text += "[He]2s²2p^6 1s²2s²2p^6";
        Carga.text += "---";
        PotenciAIonizacao.text += "21.47";
        RaioAtomico.text += "38";
        RaioCovalente.text += "69";
        RaioDeVanDerWaals.text += "154";
        Eletronegatividade.text += "---";
        CamadaValencia.text += "O";
        Afinidade.text += "0";
        CondutividadeEletrica.text += "---";
        TipoEletronico.text += "---";
        TipoMagnetico.text += "Diamagnetico";
        Sensibilidade.text += "-8.27*10^-11";
        Resistividade.text += "---";
        PontoDeSuperconducao.text += "---";
        info.text += "";
    }
     public void Sodio(){
        Nome.text = "Sodio";
        NomeLatin.text = "Natrium";
        AnoDescoberta.text += "1807";
        CAS.text += "CAS7440-23-5";
        Descobridor.text += "Humphry Davy";
        Valor.text += "1,87";
        K.text += "2";
        L.text += "8";
        M.text += "1";
        N.text += "0";
        O.text += "0";
        P.text += "0";
        Q.text += "0";
        E.text += "0";
        Eletrons.text += "11";
        Protons.text += "11";
        Neutrons.text += "12";
        Numero.text = "11";
        Simbolo.text = "Ne";
        NumeroAtomico.text += "11";
        PesoAtomico.text += "22.9897";
        Densidade.text += "0.971";
        PontoDeFusao.text += "97.8";
        PontoDeEbulicao.text += "882.94";
        Fase.text += "Solido";
        Valencia.text += "I";
        Periodo.text += "3";
        Grupo.text += "IA";
        Quadra.text += "s - quadra";
        Configuracao.text += "[Ne]3s¹ 1s²2s²2p^6 3s¹";
        Carga.text += "Na+";
        PotenciAIonizacao.text += "5.12";
        RaioAtomico.text += "190";
        RaioCovalente.text += "154";
        RaioDeVanDerWaals.text += "227";
        Eletronegatividade.text += "0.93";
        CamadaValencia.text += "I";
        Afinidade.text += "52.8";
        CondutividadeEletrica.text += "2.1*10^7";
        TipoEletronico.text += "Condutor";
        TipoMagnetico.text += "Paramagnetico";
        Sensibilidade.text += "2*10^-10";
        Resistividade.text += "4.7*10^-8";
        PontoDeSuperconducao.text += "---";
        info.text += "";
    }
     public void Magnesio(){
        Nome.text = "Magnesio";
        NomeLatin.text = "Magnesium";
        AnoDescoberta.text += "1808";
        CAS.text += "CAS7439-95-4";
        Descobridor.text += "Joseph Black";
        Valor.text += "1,27";
        K.text += "2";
        L.text += "8";
        M.text += "2";
        N.text += "0";
        O.text += "0";
        P.text += "0";
        Q.text += "0";
        E.text += "0";
        Eletrons.text += "12";
        Protons.text += "12";
        Neutrons.text += "12";
        NumeroAtomico.text += "12";
        Numero.text = "12";
        Simbolo.text = "Mg";
        PesoAtomico.text += "24.3050";
        Densidade.text += "1738";
        PontoDeFusao.text += "650.0";
        PontoDeEbulicao.text += "1090.0";
        Fase.text += "Solido";
        Valencia.text += "II";
        Periodo.text += "3";
        Grupo.text += "IIA";
        Quadra.text += "s - quadra";
        Configuracao.text += "[Ne]3s² 1s² 2s² 2p^6 3s²";
        Carga.text += "Mg2+";
        PotenciAIonizacao.text += "7.61";
        RaioAtomico.text += "160";
        RaioCovalente.text += "130";
        RaioDeVanDerWaals.text += "173";
        Eletronegatividade.text += "1.31";
        CamadaValencia.text += "II";
        Afinidade.text += "0";
        CondutividadeEletrica.text += "2.3*10^7";
        TipoEletronico.text += "Condutor";
        TipoMagnetico.text += "Paramagnetico";
        Sensibilidade.text += "1.68*10^-10";
        Resistividade.text += "4.4*10^*-8";
        PontoDeSuperconducao.text += "---";
        info.text += "";
    }
     public void Aluminio(){
        Nome.text = "Aluminio";
        NomeLatin.text = "Aluminium";
        AnoDescoberta.text += "1825";
        CAS.text += "CAS7429-90-5";
        Descobridor.text += "Hans Christian Orsted";
        Valor.text += "0.98";
        K.text += "2";
        L.text += "8";
        M.text += "3";
        N.text += "0";
        O.text += "0";
        P.text += "0";
        Q.text += "0";
        E.text += "0";
        Eletrons.text += "13";
        Protons.text += "13";
        Neutrons.text += "14";
        NumeroAtomico.text += "13";
        Numero.text = "13";
        Simbolo.text = "Al";
        PesoAtomico.text += "26.9815";
        Densidade.text += "2.6989";
        PontoDeFusao.text += "660.0";
        PontoDeEbulicao.text += "2518.82";
        Fase.text += "Solido";
        Valencia.text += "I,III";
        Periodo.text += "3";
        Grupo.text += "IIIA";
        Quadra.text += "p - quadra";
        Configuracao.text += "[Ne]3s²3p¹1s²2s²2p^6 3s² 3p¹";
        Carga.text += "Al3+";
        PotenciAIonizacao.text += "5.95";
        RaioAtomico.text += "143";
        RaioCovalente.text += "118";
        RaioDeVanDerWaals.text += "184";
        Eletronegatividade.text += "1.61";
        CamadaValencia.text += "I,III";
        Afinidade.text += "42.5";
        CondutividadeEletrica.text += "3.8*10^&";
        TipoEletronico.text += "Condutor";
        TipoMagnetico.text += "Paramagnetico";
        Sensibilidade.text += "2.1*10^-10";
        Resistividade.text += "2.6*10^-8";
        PontoDeSuperconducao.text += "1.18";
        info.text += "";
    }
     public void Silicio(){
        Nome.text = "Silicio";
        NomeLatin.text = "Silicium";
        AnoDescoberta.text += "1824";
        CAS.text += "CAS7440-21-3";
        Descobridor.text += "Jons Jakob Berzelius";
        Valor.text += "29,71";
        K.text += "2";
        L.text += "8";
        M.text += "4";
        N.text += "0";
        O.text += "0";
        P.text += "0";
        Q.text += "0";
        E.text += "0";
        Eletrons.text += "14";
        Protons.text += "14";
        Neutrons.text += "14";
        NumeroAtomico.text += "14";
        Numero.text = "14";
        Simbolo.text = "Si";
        PesoAtomico.text += "28.0855";
        Densidade.text += "2.33";
        PontoDeFusao.text += "1414.85";
        PontoDeEbulicao.text += "3265.0";
        Fase.text += "Solido";
        Valencia.text += "II,IV";
        Periodo.text += "3";
        Grupo.text += "IVA";
        Quadra.text += "p - quadra";
        Configuracao.text += "[Ne]3a²3p²1s²2s²2p^6 3s²3p²";
        Carga.text += "---";
        PotenciAIonizacao.text += "8.12";
        RaioAtomico.text += "132";
        RaioCovalente.text += "111";
        RaioDeVanDerWaals.text += "210";
        Eletronegatividade.text += "1.9";
        CamadaValencia.text += "II,IV";
        Afinidade.text += "133.6";
        CondutividadeEletrica.text += "1.10^7";
        TipoEletronico.text += "Semicondutor";
        TipoMagnetico.text += "Diamagnetico";
        Sensibilidade.text += "-4.49*10^-11";
        Resistividade.text += "0.001";
        PontoDeSuperconducao.text += "---";
        info.text += "";
    }
     public void Fosforo(){
        Nome.text = "Fosforo";
        NomeLatin.text = "Phosphorus";
        AnoDescoberta.text += "1669";
        CAS.text += "CAS7723-14-0";
        Descobridor.text += "Henning Brand";
        Valor.text += "165,04";
        K.text += "2";
        L.text += "8";
        M.text += "5";
        N.text += "0";
        O.text += "0";
        P.text += "0";
        Q.text += "0";
        E.text += "0";
        Eletrons.text += "15";
        Protons.text += "15";
        Neutrons.text += "16";
        NumeroAtomico.text += "15";
        Numero.text = "15";
        Simbolo.text = "P";
        PesoAtomico.text += "30.9737";
        Densidade.text += "2.82";
        PontoDeFusao.text += "44.15";
        PontoDeEbulicao.text += "280.5";
        Fase.text += "Solido";
        Valencia.text += "III,V";
        Periodo.text += "3";
        Grupo.text += "VA";
        Quadra.text += "p - quadra";
        Configuracao.text += "[Ne]3s²3p³1s²2s²2p^6 3s²3p³";
        Carga.text += "P³";
        PotenciAIonizacao.text += "10.3";
        RaioAtomico.text += "128";
        RaioCovalente.text += "106";
        RaioDeVanDerWaals.text += "180";
        Eletronegatividade.text += "2.19";
        CamadaValencia.text += "III,V";
        Afinidade.text += "72";
        CondutividadeEletrica.text += "1*10^7";
        TipoEletronico.text += "Condutor";
        TipoMagnetico.text += "Diamagnetico";
        Sensibilidade.text += "-3.5*10^-10";
        Resistividade.text += "1*10^-7";
        PontoDeSuperconducao.text += "---";
        info.text += "";
    }
     public void Enxofre(){
        Nome.text = "Enxofre";
        NomeLatin.text = "Sulphuris";
        AnoDescoberta.text += "<600 BCE";
        CAS.text += "CAS7704-34-9";
        Descobridor.text += "---";
        Valor.text += "275,06";
        K.text += "2";
        L.text += "8";
        M.text += "6";
        N.text += "0";
        O.text += "0";
        P.text += "0";
        Q.text += "0";
        E.text += "0";
        Eletrons.text += "16";
        Protons.text += "16";
        Neutrons.text += "16";
        NumeroAtomico.text += "16";
        Numero.text = "16";
        Simbolo.text = "S";
        PesoAtomico.text += "32.065";
        Densidade.text += "2.070";
        PontoDeFusao.text += "112.8";
        PontoDeEbulicao.text += "444.67";
        Fase.text += "Solido";
        Valencia.text += "II,IV,VI";
        Periodo.text += "3";
        Grupo.text += "VIA";
        Quadra.text += "p - quadra";
        Configuracao.text += "[Ne]3s²3p^4 1s²2s²2p^6 3s²3p^4";
        Carga.text += "S2-";
        PotenciAIonizacao.text += "10.31";
        RaioAtomico.text += "127";
        RaioCovalente.text += "102";
        RaioDeVanDerWaals.text += "180";
        Eletronegatividade.text += "2.58";
        CamadaValencia.text += "II,IV,VI";
        Afinidade.text += "200";
        CondutividadeEletrica.text += "1*10^-15";
        TipoEletronico.text += "Dieletrico";
        TipoMagnetico.text += "Diamagnetico";
        Sensibilidade.text += "-1.99*10^-10";
        Resistividade.text += "1*10^15";
        PontoDeSuperconducao.text += "---";
        info.text += "";
    }
     public void CLoro(){
        Nome.text = "Cloro";
        NomeLatin.text = "Chlorum";
        AnoDescoberta.text += "1774";
        CAS.text += "CAS7782-50-5";
        Descobridor.text += "Carl Wilhelm Scheele";
        Valor.text += "0,83";
        K.text += "2";
        L.text += "8";
        M.text += "7";
        N.text += "0";
        O.text += "0";
        P.text += "0";
        Q.text += "0";
        E.text += "0";
        Eletrons.text += "17";
        Protons.text += "17";
        Neutrons.text += "18";
        NumeroAtomico.text += "17";
        PesoAtomico.text += "35.453";
        Densidade.text += "0.003214";
        PontoDeFusao.text += "-100.98";
        PontoDeEbulicao.text += "-34.6";
        Fase.text += "Gasoso";
        Valencia.text += "I,III,V,VII";
        Periodo.text += "3";
        Grupo.text += "VIIA";
        Quadra.text += "p - quadra";
        Configuracao.text += "[Ne]3s²3p^5 1s²2s²2p^6 3s²3p^5";
        Carga.text += "Cl-";
        PotenciAIonizacao.text += "12.96";
        RaioAtomico.text += "99";
        RaioCovalente.text += "99";
        RaioDeVanDerWaals.text += "175";
        Eletronegatividade.text += "3.16";
        CamadaValencia.text += "I,III,V,VII";
        Afinidade.text += "349";
        CondutividadeEletrica.text += "0,01";
        TipoEletronico.text += "Dieletrico";
        TipoMagnetico.text += "Diamagnetico";
        Sensibilidade.text += "-5,11*10^-10";
        Resistividade.text += "100";
        PontoDeSuperconducao.text += "---";
        info.text += "";
    }
     public void Argonio(){
        Nome.text = "Argonio";
        NomeLatin.text = "Argon";
        AnoDescoberta.text += "1894";
        CAS.text += "CAS7440-37-1";
        Descobridor.text += "Sir William Ramsay";
        Valor.text += "2.75";
        K.text += "2";
        L.text += "8";
        M.text += "8";
        N.text += "0";
        O.text += "0";
        P.text += "0";
        Q.text += "0";
        E.text += "0";
        Eletrons.text += "18";
        Protons.text += "18";
        Neutrons.text += "22";
        NumeroAtomico.text += "18";
        Numero.text = "18";
        Simbolo.text = "Ar";
        PesoAtomico.text += "39.948";
        Densidade.text += "0.001784";
        PontoDeFusao.text += "-189.34";
        PontoDeEbulicao.text += "-185.85";
        Fase.text += "Gasoso";
        Valencia.text += "O";
        Periodo.text += "3";
        Grupo.text += "VIIIA";
        Quadra.text += "p - quadra";
        Configuracao.text += "[Ne]3s² 3p^6 1s²2s²2p^6 3s²3p^6";
        Carga.text += "15.68";
        PotenciAIonizacao.text += "71";
        RaioAtomico.text += "71";
        RaioCovalente.text += "97";
        RaioDeVanDerWaals.text += "188";
        Eletronegatividade.text += "---";
        CamadaValencia.text += "O";
        Afinidade.text += "0";
        CondutividadeEletrica.text += "---";
        TipoEletronico.text += "---";
        TipoMagnetico.text += "Diamagnetico";
        Sensibilidade.text += "-2.4*10^-10";
        Resistividade.text += "---";
        PontoDeSuperconducao.text += "---";
        info.text += "";
    }
     public void Potassio(){
        Nome.text = "Potassio";
        NomeLatin.text = "Kalium";
        AnoDescoberta.text += "1807";
        CAS.text += "CAS7440-09-7";
        Descobridor.text += "Humphry Davy";
        Valor.text += "7,54";
        K.text += "2";
        L.text += "8";
        M.text += "8";
        N.text += "1";
        O.text += "0";
        P.text += "0";
        Q.text += "0";
        E.text += "0";
        Eletrons.text += "19";
        Protons.text += "19";
        Neutrons.text += "20";
        NumeroAtomico.text += "19";
        Numero.text = "19";
        Simbolo.text = "K";
        PesoAtomico.text += "39.0983";
        Densidade.text += "0.856";
        PontoDeFusao.text += "63.38";
        PontoDeEbulicao.text += "758.8";
        Fase.text += "Solido";
        Valencia.text += "I";
        Periodo.text += "4";
        Grupo.text += "IA";
        Quadra.text += "s - quadra";
        Configuracao.text += "[Ar]4s¹1s²2s²2p^6 3s²3p^6 4s¹";
        Carga.text += "K+";
        PotenciAIonizacao.text += "4.32";
        RaioAtomico.text += "235";
        RaioCovalente.text += "196";
        RaioDeVanDerWaals.text += "275";
        Eletronegatividade.text += "0.82";
        CamadaValencia.text += "I";
        Afinidade.text += "48.4";
        CondutividadeEletrica.text += "1.4*10^7";
        TipoEletronico.text += "Condutor";
        TipoMagnetico.text += "---";
        Sensibilidade.text += "3.62*10^-10";
        Resistividade.text += "---";
        PontoDeSuperconducao.text += "---";
        info.text += "";
    }
     public void Calcio(){
        Nome.text = "Calcio";
        NomeLatin.text = "Calcium";
        AnoDescoberta.text += "1808";
        CAS.text += "CAS7440-70-2";
        Descobridor.text += "Humphry Davy";
        Valor.text += "1.29";
        K.text += "2";
        L.text += "8";
        M.text += "8";
        N.text += "2";
        O.text += "0";
        P.text += "0";
        Q.text += "0";
        E.text += "0";
        Eletrons.text += "20";
        Protons.text += "20";
        Neutrons.text += "20";
        NumeroAtomico.text += "20";
        Numero.text = "20";
        Simbolo.text = "Ca";
        PesoAtomico.text += "40.078";
        Densidade.text += "1.55";
        PontoDeFusao.text += "842.0";
        PontoDeEbulicao.text += "1484.0";
        Fase.text += "Solido";
        Valencia.text += "II";
        Periodo.text += "4";
        Grupo.text += "IIA";
        Quadra.text += "s - quadra";
        Configuracao.text += "[Ar]4s²1s²2s²2p^6 3s²3p^6 4s²";
        Carga.text += "Ca2+";
        PotenciAIonizacao.text += "6.09";
        RaioAtomico.text += "197";
        RaioCovalente.text += "174";
        RaioDeVanDerWaals.text += "231";
        Eletronegatividade.text += "1";
        CamadaValencia.text += "II";
        Afinidade.text += "2.37";
        CondutividadeEletrica.text += "2.9*10^7";
        TipoEletronico.text += "Condutor";
        TipoMagnetico.text += "Paramagnetico";
        Sensibilidade.text += "5.531*10^-10";
        Resistividade.text += "3.4*10^-8";
        PontoDeSuperconducao.text += "---";
        info.text += "";
    }
    public void Escandio(){
        Nome.text = "Escandio";
        NomeLatin.text = "Scandium";
        AnoDescoberta.text += "1879";
        CAS.text += "CAS7440-20-2";
        Descobridor.text += "Lars Fredik Nilson";
        Valor.text += "1903.42";
        K.text += "2";
        L.text += "8";
        M.text += "9";
        N.text += "2";
        O.text += "0";
        P.text += "0";
        Q.text += "0";
        E.text += "0";
        Eletrons.text += "21";
        Protons.text += "21";
        Neutrons.text += "21";
        NumeroAtomico.text += "21";
        Numero.text = "21";
        Simbolo.text = "Sc";
        PesoAtomico.text += "44.9559";
        Densidade.text += "2.99";
        PontoDeFusao.text += "1541.0";
        PontoDeEbulicao.text += "2836.0";
        Fase.text += "Solido";
        Valencia.text += "III";
        Periodo.text += "4";
        Grupo.text += "IIIB";
        Quadra.text += "d - quadra";
        Configuracao.text += "[Ar]4s²3d¹1s²2s²2p^6 3s²4s²3d¹";
        Carga.text += "Sc3+";
        PotenciAIonizacao.text += "6.57";
        RaioAtomico.text += "162";
        RaioCovalente.text += "144";
        RaioDeVanDerWaals.text += "211";
        Eletronegatividade.text += "1.36";
        CamadaValencia.text += "III";
        Afinidade.text += "18.1";
        CondutividadeEletrica.text += "1.8*10^6";
        TipoEletronico.text += "Condutor";
        TipoMagnetico.text += "---";
        Sensibilidade.text += "3.956*10^-9";
        Resistividade.text += "5.5*10^-7";
        PontoDeSuperconducao.text += "0.05";
        info.text += "";
    }
     public void Titanio(){
        Nome.text = "Titanio";
        NomeLatin.text = "Titanium";
        AnoDescoberta.text += "1795";
        CAS.text += "CAS7440-32-6";
        Descobridor.text += "William Gregor";
        Valor.text += "3636.31";
        K.text += "2";
        L.text += "8";
        M.text += "10";
        N.text += "2";
        O.text += "0";
        P.text += "0";
        Q.text += "0";
        E.text += "0";
        Eletrons.text += "22";
        Protons.text += "22";
        Neutrons.text += "22";
        NumeroAtomico.text += "22";
        Numero.text = "22";
        Simbolo.text = "Ti";
        PesoAtomico.text += "47.867";
        Densidade.text += "4.54";
        PontoDeFusao.text += "1660.0";
        PontoDeEbulicao.text += "3287.0";
        Fase.text += "Solido";
        Valencia.text += "II,III,IV";
        Periodo.text += "4";
        Grupo.text += "IVB";
        Quadra.text += "d - quadra";
        Configuracao.text += "[Ar]4s²3d²1s²2s²2p^6 4s²3d²";
        Carga.text += "Ti4+, Ti3+";
        PotenciAIonizacao.text += "6.81";
        RaioAtomico.text += "147";
        RaioCovalente.text += "136";
        RaioDeVanDerWaals.text += "---";
        Eletronegatividade.text += "1.54";
        CamadaValencia.text += "II,III,IV";
        Afinidade.text += "7.6";
        CondutividadeEletrica.text += "2.8*10^6";
        TipoEletronico.text += "Condutor";
        TipoMagnetico.text += "Paramagnetico";
        Sensibilidade.text += "1.919*10^-9";
        Resistividade.text += "4*10^-7";
        PontoDeSuperconducao.text += "0.4";
        info.text += "";
    }
     public void Vanadio(){
        Nome.text = "Vanadio";
        NomeLatin.text = "Vanadium";
        AnoDescoberta.text += "1830";
        CAS.text += "CAS7440-62-2";
        Descobridor.text += "Andres Manuel del Rio";
        Valor.text += "1298.29";
        K.text += "2";
        L.text += "8";
        M.text += "11";
        N.text += "2";
        O.text += "0";
        P.text += "0";
        Q.text += "0";
        E.text += "0";
        Eletrons.text += "23";
        Protons.text += "23";
        Neutrons.text += "23";
        NumeroAtomico.text += "23";
        Numero.text = "23";
        Simbolo.text = "V";
        PesoAtomico.text += "50.9415";
        Densidade.text += "6.11";
        PontoDeFusao.text += "1910.0";
        PontoDeEbulicao.text += "3407.0";
        Fase.text += "Solido";
        Valencia.text += "II,III,IV,V";
        Periodo.text += "4";
        Grupo.text += "VB";
        Quadra.text += "d - quadra";
        Configuracao.text += "[Ar]4s²3d³1s²2s²2p^6 3s²3p^6 4s²3d³";
        Carga.text += "V3+,V5+";
        PotenciAIonizacao.text += "6.76";
        RaioAtomico.text += "134";
        RaioCovalente.text += "125";
        RaioDeVanDerWaals.text += "---";
        Eletronegatividade.text += "1.63";
        CamadaValencia.text += "II,III,IV,V";
        Afinidade.text += "50.6";
        CondutividadeEletrica.text += "5*10^6";
        TipoEletronico.text += "Condutor";
        TipoMagnetico.text += "---";
        Sensibilidade.text += "3.199*10^-9";
        Resistividade.text += "2*10^-7";
        PontoDeSuperconducao.text += "5.4";
        info.text += "";
    }
     public void Cromio(){
        Nome.text = "Cromio";
        NomeLatin.text = "Chromium";
        AnoDescoberta.text += "1797";
        CAS.text += "CAS7440-74-3";
        Descobridor.text += "Louis Nicolas Vauquelin";
        Valor.text += "37.08";
        K.text += "2";
        L.text += "8";
        M.text += "13";
        N.text += "1";
        O.text += "0";
        P.text += "0";
        Q.text += "0";
        E.text += "0";
        Eletrons.text += "24";
        Protons.text += "24";
        Neutrons.text += "28";
        NumeroAtomico.text += "24";
        Numero.text = "24";
        Simbolo.text = "Cr";
        PesoAtomico.text += "51.9961";
        Densidade.text += "7.19";
        PontoDeFusao.text += "1907.0";
        PontoDeEbulicao.text += "2672.0";
        Fase.text += "Solido";
        Valencia.text += "II,III,VI";
        Periodo.text += "4";
        Grupo.text += "VIB";
        Quadra.text += "d - quadra";
        Configuracao.text += "[Ar]2s¹3d^5 1s²2s²2p^63s²3p^6 4s¹3s^5";
        Carga.text += "Cr3+,Cr2+";
        PotenciAIonizacao.text += "6.74";
        RaioAtomico.text += "130";
        RaioCovalente.text += "127";
        RaioDeVanDerWaals.text += "---";
        Eletronegatividade.text += "1.66";
        CamadaValencia.text += "II,III,VI";
        Afinidade.text += "64.3";
        CondutividadeEletrica.text += "7.9*10^6";
        TipoEletronico.text += "Condutor";
        TipoMagnetico.text += "Antiferromagnetico";
        Sensibilidade.text += "2.314*10^-9";
        Resistividade.text += "1.3*10^-7";
        PontoDeSuperconducao.text += "---";
        info.text += "";
    }
     public void Manganes(){
        Nome.text = "Manganes";
        NomeLatin.text = "Manganum";
        AnoDescoberta.text += "1774";
        CAS.text += "CAS7439-96-5";
        Descobridor.text += "Johan Gottlieb Gahn";
        Valor.text += "";
        K.text += "2";
        L.text += "8";
        M.text += "13";
        N.text += "2";
        O.text += "0";
        P.text += "0";
        Q.text += "0";
        E.text += "0";
        Eletrons.text += "25";
        Protons.text += "25";
        Neutrons.text += "30";
        NumeroAtomico.text += "25";
        Numero.text = "25";
        Simbolo.text = "Mn";
        PesoAtomico.text += "54,9380";
        Densidade.text += "7.21";
        PontoDeFusao.text += "1245.0";
        PontoDeEbulicao.text += "2061.0";
        Fase.text += "Solido";
        Valencia.text += "I,II,III,IV,V,VI,VII";
        Periodo.text += "4";
        Grupo.text += "VIIB";
        Quadra.text += "d - quadra";
        Configuracao.text += "[Ar]4s²3d^5 1s²2s²2p^6 3s23p^6 3s²3d^5";
        Carga.text += "Mn2+,Mn4+";
        PotenciAIonizacao.text += "7.40";
        RaioAtomico.text += "127";
        RaioCovalente.text += "139";
        RaioDeVanDerWaals.text += "---";
        Eletronegatividade.text += "1.55";
        CamadaValencia.text += "I,II,III,IV,V,VI,VII";
        Afinidade.text += "0";
        CondutividadeEletrica.text += "6.2*10^5";
        TipoEletronico.text += "Condutor";
        TipoMagnetico.text += "Paramagnetico";
        Sensibilidade.text += "6.6475*10^-9";
        Resistividade.text += "1.6*10^-7";
        PontoDeSuperconducao.text += "---";
        info.text += "";
    }
     public void Ferro(){
        Nome.text = "Ferro";
        NomeLatin.text = "Ferrum";
        AnoDescoberta.text += "Antiguidade Profunda";
        CAS.text += "CAS7439-89-6";
        Descobridor.text += "---";
        Valor.text += "";
        K.text += "2";
        L.text += "8";
        M.text += "14";
        N.text += "2";
        O.text += "0";
        P.text += "0";
        Q.text += "0";
        E.text += "0";
        Eletrons.text += "26";
        Protons.text += "26";
        Neutrons.text += "30";
        Numero.text = "26";
        Simbolo.text = "Fe";
        NumeroAtomico.text += "26";
        PesoAtomico.text += "55.845";
        Densidade.text += "7.88";
        PontoDeFusao.text += "1539.0";
        PontoDeEbulicao.text += "2862.0";
        Fase.text += "Solido";
        Valencia.text += "II,III,VI";
        Periodo.text += "4";
        Grupo.text += "VIIIB";
        Quadra.text += "d - quadra";
        Configuracao.text += "";
        Carga.text += "Fe3+,Fe2+";
        PotenciAIonizacao.text += "7.83";
        RaioAtomico.text += "126";
        RaioCovalente.text += "125";
        RaioDeVanDerWaals.text += "---";
        Eletronegatividade.text += "";
        CamadaValencia.text += "";
        Afinidade.text += "";
        CondutividadeEletrica.text += "";
        TipoEletronico.text += "";
        TipoMagnetico.text += "";
        Sensibilidade.text += "";
        Resistividade.text += "";
        PontoDeSuperconducao.text += "";
        info.text += "";
    }
     public void Cobalto(){
        Nome.text = "";
        NomeLatin.text = "";
        AnoDescoberta.text += "";
        CAS.text += "";
        Descobridor.text += "";
        Valor.text += "";
        K.text += "0";
        L.text += "0";
        M.text += "0";
        N.text += "0";
        O.text += "0";
        P.text += "0";
        Q.text += "0";
        E.text += "0";
        Eletrons.text += "";
        Protons.text += "";
        Neutrons.text += "";
        NumeroAtomico.text += "";
        Numero.text = "";
        Simbolo.text = "";
        PesoAtomico.text += "";
        Densidade.text += "";
        PontoDeFusao.text += "";
        PontoDeEbulicao.text += "";
        Fase.text += "";
        Valencia.text += "";
        Periodo.text += "";
        Grupo.text += "";
        Quadra.text += "";
        Configuracao.text += "";
        Carga.text += "";
        PotenciAIonizacao.text += "";
        RaioAtomico.text += "";
        RaioCovalente.text += "";
        RaioDeVanDerWaals.text += "";
        Eletronegatividade.text += "";
        CamadaValencia.text += "";
        Afinidade.text += "";
        CondutividadeEletrica.text += "";
        TipoEletronico.text += "";
        TipoMagnetico.text += "";
        Sensibilidade.text += "";
        Resistividade.text += "";
        PontoDeSuperconducao.text += "";
        info.text += "";
    }
    
}
